### PR TITLE
Add metric initializing log

### PR DESCRIPTION
**Pull request by Anpanman113**
Add metric initializing log

-- delete the glog in the netlink metric
-- add metric initializing log in the collector.go

### CODE REVIEW

**Comment by jingyuanliang** [comment]
Could you fix the git commit message?

**Review by MrHohn — COMMENTED** [review]
Humm, looks like the actual changes went missing - could you try to push the commit again?

**Comment by aojea** [comment]
> Humm, looks like the actual changes went missing - could you try to push the commit again?

it says they were commited yesterday 🤔

**Comment by aojea** [comment]
> > Humm, looks like the actual changes went missing - could you try to push the commit again?
> 
> it says they were commited yesterday 🤔

lol, too late for these things, disconnecting now, they were commited yesterday on the PR, it seems that the commits revert themselves or something like that

**Comment by Anpanman113** [comment]
Sorry for the confusion, I added a commit message that should not exist through Github desktop yesterday when I was trying to change the original commit message, and I will fix it

**Comment by jingyuanliang** [comment]
Your commit 2392fde looks good. You can reset your master branch to 2392fde and reopen this PR.

**Review by MrHohn — APPROVED** [review]
Both the commits and code change look good now. Thanks @Anpanman113! 
/lgtm
/approve

**Pull request merged**
