### PR TITLE
Update containerd and cni plugins

### PR DESCRIPTION
**Pull request by aojea**
update containerd dependency on tools just to silent dependabot since is not really a problem

Update the rest of dependencies for a better ~higiene~  hygiene on the project

### CODE REVIEW

**Comment by jingyuanliang** [comment]
higiene is Portuguese.

**Comment by jingyuanliang** [comment]
could you upstream `tools/` changes to [thockin/go-build-template](https://github.com/thockin/go-build-template)?

**Comment by MrHohn** [comment]
Well, didn't realize approve apply lgtm label as well :)

**Comment by aojea** [comment]
> Well, didn't realize approve apply lgtm label as well :)

this is new , isn't it?

**Pull request merged**
