### PR TITLE
Replace sed commands with bash pattern substitution in install-cni.sh

### PR DESCRIPTION
**Pull request by jingyuanliang**
This removes all use of `sed` command from netd-init.

/assign @MrHohn

### CODE REVIEW

**Comment by MrHohn** [comment]
@jingyuanliang question before getting these replace PRs in - what is the motivation of replacing various tools and what kind of improvement we will gain?

**Comment by jingyuanliang** [comment]
All these are replaced with shell built-ins. Hoping to eliminate a few forks / external program calls. I also think the syntax is more clear in the replacements.

**Comment by jingyuanliang** [comment]
Merging into https://github.com/GoogleCloudPlatform/netd/pull/169

**Pull request closed without merging**
