### PR TITLE
Update release notes for 0.2.9

### PR DESCRIPTION
**Pull request by AnishShah**
Signed-off-by: Anish Shah <anishshah@google.com>

### CODE REVIEW

**Comment by AnishShah** [comment]
@lzang @skmatti

**Review by MrHohn — APPROVED** [review]
Merging to release a new version.
/lgtm
/approve

**Comment by MrHohn** [comment]
I believe this is picking up https://github.com/GoogleCloudPlatform/netd/pull/101 in the new release.

**Pull request merged**
