### PR TITLE
Remove Go version 1.18 from GitHub Actions

### PR DESCRIPTION
**Pull request by yiningou**

### CODE REVIEW

**Comment by jingyuanliang** [comment]
Could you squash it?

**Comment by yiningou** [comment]
> Could you squash it?

Done.

**Comment by jingyuanliang** [comment]
There's a typo in commit message (uppercase I) but don't bother to have another round of revision.
/lgtm
/approve

**Comment by yiningou** [comment]
> There's a typo in commit message (uppercase I) but don't bother to have another round of revision. /lgtm /approve

Sorry for the confusion. Thank you for pointing it out!

**Pull request merged**
